import { Property } from "@/types";

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Modern Family Home in San Jose del Monte",
    description:
      "A beautifully designed modern home in a quiet subdivision. Perfect for families looking for comfort and security.",
    price: 4500000,
    type: "sale",
    status: "available",
    bedrooms: 4,
    bathrooms: 3,
    area: 120,
    garage: 2,
    location: "San Jose del Monte, Bulacan",
    subdivision: "Palmera Homes",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    ],
    featured: true,
    created_at: "2024-01-01",
  },
  {
    id: "2",
    title: "Affordable Townhouse in Meycauayan",
    description:
      "Move-in ready townhouse with modern finishes. Close to schools, malls, and public transport.",
    price: 2800000,
    type: "sale",
    status: "available",
    bedrooms: 3,
    bathrooms: 2,
    area: 80,
    garage: 1,
    location: "Meycauayan, Bulacan",
    subdivision: "Villa Rosario Subdivision",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
    ],
    featured: true,
    created_at: "2024-01-02",
  },
  {
    id: "3",
    title: "Spacious Condo for Rent in Quezon City",
    description:
      "Fully furnished condo unit with stunning city views. Ideal for young professionals and small families.",
    price: 25000,
    type: "rent",
    status: "available",
    bedrooms: 2,
    bathrooms: 1,
    area: 55,
    garage: 1,
    location: "Quezon City, Metro Manila",
    subdivision: "One Eastwood Avenue",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    featured: true,
    created_at: "2024-01-03",
  },
  {
    id: "4",
    title: "House & Lot for Sale in Marilao",
    description:
      "Corner lot property in a gated community. Bright, airy, and ready for occupancy.",
    price: 3200000,
    type: "sale",
    status: "available",
    bedrooms: 3,
    bathrooms: 2,
    area: 95,
    garage: 1,
    location: "Marilao, Bulacan",
    subdivision: "Camella Marilao",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    featured: false,
    created_at: "2024-01-04",
  },
  {
    id: "5",
    title: "Commercial Space for Rent in Bocaue",
    description:
      "Prime commercial space along the main highway. High foot traffic, ideal for retail or office use.",
    price: 35000,
    type: "rent",
    status: "available",
    bedrooms: 0,
    bathrooms: 1,
    area: 75,
    location: "Bocaue, Bulacan",
    subdivision: "Bocaue Commercial Complex",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    ],
    featured: false,
    created_at: "2024-01-05",
  },
  {
    id: "6",
    title: "Elegant House in Caloocan",
    description:
      "Newly built elegant home with premium finishes. Located in a peaceful village with 24/7 security.",
    price: 6800000,
    type: "sale",
    status: "available",
    bedrooms: 5,
    bathrooms: 4,
    area: 200,
    location: "Caloocan, Metro Manila",
    subdivision: "Filinvest 2 Village",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    ],
    featured: true,
    created_at: "2024-01-06",
  },
  {
    id: "7",
    title: "Ready for Occupancy Townhouse in Caloocan",
    description:
      "Brand new two-storey townhouse with modern interior finishes. Features a spacious living area, covered parking, and 24/7 security. Ideal for young families.",
    price: 3800000,
    type: "sale",
    status: "available",
    bedrooms: 3,
    bathrooms: 2,
    area: 88,
    location: "Caloocan, Metro Manila",
    subdivision: "Metro Gate Subdivision",
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80",
    ],
    featured: true,
    created_at: "2024-01-07",
  },
  {
    id: "8",
    title: "Cozy Studio Unit for Rent in Marilao",
    description:
      "Fully furnished studio unit perfect for students and young professionals. Just minutes away from NLEX and major highways.",
    price: 12000,
    type: "rent",
    status: "available",
    bedrooms: 1,
    bathrooms: 1,
    area: 28,
    location: "Marilao, Bulacan",
    subdivision: "Crown Asia Condominiums",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    featured: false,
    created_at: "2024-01-08",
  },
  {
    id: "9",
    title: "Vacant Lot for Sale in San Jose del Monte",
    description:
      "Prime vacant lot in a fast-growing residential area. Perfect for building your dream home or as an investment property. Titled and ready for transfer.",
    price: 1800000,
    type: "sale",
    status: "available",
    bedrooms: 0,
    bathrooms: 0,
    area: 150,
    location: "San Jose del Monte, Bulacan",
    subdivision: "Verdana Homes",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    ],
    featured: false,
    created_at: "2024-01-09",
  },
];